/* Generated by Opal 0.9.2 */
Opal.modules["opal/connect"] = function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $module = Opal.module;

  return (function($base) {
    var $Opal, self = $Opal = $module($base, 'Opal');

    var def = self.$$proto, $scope = self.$$scope;

    (function($base) {
      var $Connect, self = $Connect = $module($base, 'Connect');

      var def = self.$$proto, $scope = self.$$scope;

      nil
    })($scope.base)
  })($scope.base)
};

/* Generated by Opal 0.9.2 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var $a, $b, TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$require', '$ready?', '$html', '$[]', '$append', '$foo', '$new']);
  self.$require("opal/connect");
  module.hot.accept();
  require('./.connect-requires');
  return ($a = ($b = $scope.get('Document'))['$ready?'], $a.$$p = (TMP_1 = function(){var self = TMP_1.$$s || this;

  $scope.get('Element')['$[]']("body").$html("");
    $scope.get('Element')['$[]']("body").$append("<div>from hello.rb</div>");
    return $scope.get('A').$new().$foo();}, TMP_1.$$s = self, TMP_1), $a).call($b);
})(Opal);
